### ISSUE TITLE
Could not load 'plugins/FBasics.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by k3ldon** [Sudzzy/FBasics#4]
Hi!, i have this issue always i can use this plugin but with the last build i cannot...

[09:41:03] [Server thread/INFO]: Busy Connections:

[09:41:03] [Server thread/ERROR]: Could not load 'plugins/FBasics.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: com.avaje.ebeaninternal.server.lib.sql.DataSourceException: java.sql.SQLException: Access denied for user 'bukkit'@'localhost' (using password: YES)
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugins(CraftServer.java:290) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:152) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_72]
Caused by: com.avaje.ebeaninternal.server.lib.sql.DataSourceException: java.sql.SQLException: Access denied for user 'bukkit'@'localhost' (using password: YES)
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.<init>(DataSourcePool.java:220) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourceManager.getDataSource(DataSourceManager.java:217) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourceGlobalManager.getDataSource(DataSourceGlobalManager.java:63) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.getDataSourceFromConfig(DefaultServerFactory.java:431) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.setDataSource(DefaultServerFactory.java:392) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:168) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.java.JavaPlugin.init(JavaPlugin.java:373) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:128) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.originmc.fbasics.FBasics.<init>(FBasics.java:24) ~[FBasics.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_72]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_72]
	at java.lang.Class.newInstance(Class.java:379) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	... 6 more
Caused by: java.sql.SQLException: Access denied for user 'bukkit'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_72]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_72]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at java.sql.DriverManager.getConnection(DriverManager.java:571) ~[?:1.7.0_72]
	at java.sql.DriverManager.getConnection(DriverManager.java:187) ~[?:1.7.0_72]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.createUnpooledConnection(DataSourcePool.java:396) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.createConnectionForQueue(DataSourcePool.java:602) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.lib.sql.PooledConnectionQueue.ensureMinimumConnections(PooledConnectionQueue.java:205) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.initialise(DataSourcePool.java:258) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourcePool.<init>(DataSourcePool.java:218) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourceManager.getDataSource(DataSourceManager.java:217) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.lib.sql.DataSourceGlobalManager.getDataSource(DataSourceGlobalManager.java:63) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.getDataSourceFromConfig(DefaultServerFactory.java:431) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.setDataSource(DefaultServerFactory.java:392) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:168) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:63) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:78) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.java.JavaPlugin.init(JavaPlugin.java:373) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:128) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.originmc.fbasics.FBasics.<init>(FBasics.java:24) ~[FBasics.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_72]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_72]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_72]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_72]
	at java.lang.Class.newInstance(Class.java:379) ~[?:1.7.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-c46583f-e6f9fd4]
	... 6 more

**Comment by Sudzzy** [comment]
This looks like there are too many plugins accessing Bukkit's database.

**Comment by Sudzzy** [comment]
@k3ldon Any updates on this issue?

**Comment by k3ldon** [comment]
yes now works, but the plugin check first bukkit.yml

**Comment by Sudzzy** [comment]
Glad you've got it resolved!
