### ISSUE TITLE
Inventory error event

### ISSUE THREAD

**Issue by drizzerx** [Sudzzy/FBasics#5]
22:01:25] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to FBasics v1.4.0
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1620]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1620]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1620]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1620]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:725) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.EntityPlayer.startCrafting(EntityPlayer.java:590) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.BlockWorkbench.interact(SourceFile:40) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:384) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:662) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1620]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1620]
Caused by: java.lang.IllegalStateException: Start block missed in BlockIterator
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:170) ~[spigot.jar:git-Spigot-1620]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:233) ~[spigot.jar:git-Spigot-1620]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:268) ~[spigot.jar:git-Spigot-1620]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:132) ~[spigot.jar:git-Spigot-1620]
	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:158) ~[spigot.jar:git-Spigot-1620]
	at org.originmc.fbasics.listeners.ChestDupeListener.onInventoryOpen(ChestDupeListener.java:103) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor303.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_71]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_71]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1620]
	... 17 more
[22:01:25] [Server thread/INFO]: Edii33 issued server command: /msg carlosgaymer787 mrtutorialesedu
[22:01:26] [Server thread/INFO]: Tina06 issued server command: /jobs loin minero
[22:01:26] [Server thread/ERROR]: Could not pass event InventoryOpenEvent to FBasics v1.4.0
org.bukkit.event.EventException

**Comment by Sudzzy** [comment]
This error breaks nothing and am aware of it. Bukkit is the one that throws the error, but I can add an exception to prevent people from reporting this. Right now though seeing this error is causing you no harm at all.

**Comment by Sudzzy** [comment]
Updated dev version to fix this.
