### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by k3ldon** [Sudzzy/FBasics#7]
can not start... with the last build

[06:34:12] [Server thread/ERROR]: Error occurred while enabling FBasics v1.5.0-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/originmc/hooks/factions/FactionsManager
	at org.originmc.fbasics.FBasics.onEnable(FBasics.java:56) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader.enablePlugin(PerWorldPluginLoader.java:145) [PerWorldPlugins.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.ClassNotFoundException: org.originmc.hooks.factions.FactionsManager
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372) ~[?:1.8.0_31]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.8.0_31]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_31]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-R0.1-SNAPSHOT.jar:git-Spigot-35348a5-ee6d0fa]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_31]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_31]
	... 13 more

**Comment by Sudzzy** [comment]
What version of factions are you using?

**Comment by k3ldon** [comment]
im using...

Factions v2.7.4
MassiveCore 2.7.4

**Comment by Sudzzy** [comment]
Fixed, thanks for the report.
