### ISSUE TITLE
Crahs at launch

### ISSUE THREAD

**Issue by Technowix** [Sudzzy/FBasics#8]
[14:53:35] [Server thread/INFO]: [FBasics] Enabling FBasics v1.5.0-SNAPSHOT
[14:53:35] [Server thread/ERROR]: Error occurred while enabling FBasics v1.5.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at org.originmc.fbasics.FBasics.onEnable(FBasics.java:48) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-35348a5-ee6d0fa]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]

Really don't know what is going on... :x

**Comment by Sudzzy** [comment]
You need to have Vault on the server also.

**Comment by Technowix** [comment]
They are here :p ! Maybe that cause i use the "very lastest" version ? ^^

**Comment by Sudzzy** [comment]
No, it's been part of the plugin since 1.4.0 I think. I'll go ahead and close this now anyways.
